insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Finance','4','50','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','4','50','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Public','Media','4','10000','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Public','Media','3','10000','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','5','200','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Public','Finance','4','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','4','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','4','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Public','Finance','4','10000','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','4','200','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Finance','4','200','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','4','200','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Public','Insurance','3','10000','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','3','20','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Media','5','200','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Public','Insurance','4','1000','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Insurance','4','10000','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','4','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','4','50','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Public','Business Services','4','50','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','3','1000','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','4','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','4','1000','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','5','200','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Accounting & Legal','3','50','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','3','50','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','3','50','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','4','1000','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Insurance','4','10000','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Public','Retail','3','10000','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','5','200','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Public','Finance','4','10000','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Public','Business Services','3','10000','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','4','10000','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','3','10000','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','5','10000','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Public','Insurance','4','10000','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','4','10000','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','4','10000','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('College / University','Education','4','50','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','4','50','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Contract','Business Services','4','50','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Manufacturing','4','50','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','4','200','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Accounting & Legal','4','50','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','5','50','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','5','50','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','3','50','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Accounting & Legal','4','200','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','3','200','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','3','200','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Education','4','200','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','4','200','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','4','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','4','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Public','Business Services','4','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','5','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Manufacturing','4','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','3','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Public','Business Services','4','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','4','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','4','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Finance','4','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Public','Insurance','3','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Public','Health Care','3','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Travel & Tourism','4','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Public','Finance','3','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','4','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','5','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Public','Business Services','4','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','4','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','3','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Public','Business Services','3','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','3','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Public','Business Services','4','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Insurance','3','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Public','Aerospace & Defense','3','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Health Care','3','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Manufacturing','3','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','3','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Accounting & Legal','4','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Manufacturing','3','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Insurance','3','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','4','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Accounting & Legal','3','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','4','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Business Services','5','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Retail','3','100','Business Analyst','186');
insert into ba(Type_ownership,Sector,Rating,Size,Job_title,(select max(Salary_Estimate_k) from ba)) values('Company - Private','Health Care','3','1000','Business Analyst','186');
